### ISSUE TITLE
Feature request: function taking spell name or spell id as argument

### ISSUE THREAD

**Issue by mrbuds** [Ennea/LibClassicSpellActionCount-1.0#1]
Hello, I'm one of the maintainers of the classic version of WeakAuras and i am thinking to include this lib.
Do you think a function that take it spell name or id as argument instead of action bar slot could be added to your library ?

**Comment by Ennea** [comment]
Sure :) I will add a function for getting the action count from the spell ID. I will look into spell name also, but I haven't tried using GetSpellInfo() with the spell name so far. Shouldn't be an issue assuming it works well ;)
