### ISSUE TITLE
Error loading LibStub 

### ISSUE THREAD

**Issue by Desik** [Ennea/LibClassicSpellActionCount-1.0#2]
`21x Error loading LibClassicSpellActionCount-1.0-3\LibStub\LibStub-1.0.2-70000.lua`

Getting this error on login, seems like the LibClassicSpellActionCount-1.0 folder is not pulling the LibStub folder when packaging.

**Comment by Ennea** [comment]
Oh.. right. I kind of stopped packaging LibStub with LibClassicSpellActionCount, as it would typically be embedded in any addon that uses it. Or so I thought, anyway. If you want to have the lib as a standalone, I guess you can just drop in LibStub yourself for now. And I will make sure to package it again in future versions. Will that work for you?
